version: "3"
services:
  db:
    image: docker.io/postgres:17
    container_name: durmetrics-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "password"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
